language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "mmpiOeV/SG3/9lnWAG+3BvBQMZ37KzxhpckS158XdBJ1rYQFlTVsFAlmsnfDJbpJUQzyjJXCvIQQr7gXjv1yyXPu04ePeZ0YrtvcUNOdfDi83sf/XFv6H2A9/ZanApXbljX++6l98aUGxat3tXDLwsWeiyG+B/qr233nM1kl5n7CbRlUZZ5OnfBp/pieOspaa3QFqysV3lj9R1n7bSkP794txjU82shV7nYPZ1pl3OTE6x6kS/hemzyALFDZq5ZquP03X9e3SkpuRdNuN9/qZ7ZEfiWhqeLffsMxoo/CV2wKfceTHj0gBuYCSH3DleClpQCkZ91wIswwMYdSRtDCnCJOd9OS7fC6pe0hvYsJSwr3DYRHLnpZQXrxOfDDEzT6dK8M9dYW/8carU8Ju5AYeQ4XTOhalIQwlaiZWcE6/4epeVAUV1wglSUFI7P8ubzecvnWbSATj0DIfGw7bWi1TfRqAmFUwM1nl2Pit8EXLE6sObMc4auR+glkPw7wzNr5zaUVFynHKhcVtO3vLVe5Qun5CjWWGXOTVM2PADFpDmtkmtbakowyR2i8CzHQRIMsPdYXX06xI38F0qN/WnXXuAeVIgLD88S8SlOUU7FsGvtBJ9nRFQ1wnlmBv6IIb+t1ZspPHufXnFsatMCQ38lJDJnVq3hGbExinCQJuo6rfkU="
    - secure: "E84kf8XbuImThAukQi+QSFEkErkwi9WYBcWVEjWeC/CsoeLgi+nJ1DlNfnr9RvSUjSUAjDYXW/eK1i7VI4H+jOFYVopnKCYOFvT5ZKcfw7DlfN6b0ylrh/tCbGFOt1rx0oQMpWFGAg2PZAsoL/Fb6nAlAEUaJpDdui3XI17wjXO4pe3cH69YvOXgfRNiz4Llg9uEcMJRiJPcKs3ayMTawe2u1ws9mAzuGx4aQV7BJDsvkkyr90D7kJCVpNr+QyryCX72Ly/H3Daq4WhIHv73LLU1UpspMZwlJj/cs6v4zIzaqwdj0Qf/E2JN+Q6IDQEKpoUVhhr4gyFFXxhYPUWlN80zaUkybrexN15oUmL8O4Q6ZwlCNrNws8o9Thm92aAt3yeDtF2IH7yhq4ydDFkPzWZoHWDd6thWxI1CvePq0sHrzTKvXTX7JtjR23iifVv6zaybcYBOnbrRwQeevUF7E5zeAXA++iFwUn87mtoknhyVmoNmQMoZZZDfnPbD7fBYXTg7Nziqs3B2BBZJV6Qykvo/VqRD4N3kPPOpGzNbnqFxmmx2n/V81IrqLeqTa+orxJpBqcmrHbAo1/ibqQb7j/9cnDT0R8FD7nPrMDlzjaEMqMPkxiE1vxLG91oIRg4SF94cIl3LWF8pI+daEJstHTardyuBFzRw/bUcx7wqR/M="

install:
  mvn validate

script:
  mvn package

deploy:
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "build-artifacts.library.ucla.edu"
    local_dir: target/build-artifact
    upload_dir: sinai-web
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    on:
      branch: develop
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "build-artifacts.library.ucla.edu"
    local_dir: target/build-artifact
    upload_dir: sinai-web
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    on:
      tags: true

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: never
  slack:
    secure: eMZgS79kzSH6opY2sSJhrYdTg0jLB/JzLEvQFcn6xoDtek3/WjWWg4+M8sYv/qPqwzY3jeJ0vxd8SIwcgBJkgOHVJqvmqxWV49/F8EOENaDU+oWo5vUUh8GvM1e+B/4wZd14PbD6w9m4qs1gIAUcPECE21p0KDtvN/VYnH+96LI=

sudo: false
