language: java

jdk:
  - openjdk8

install:
  mvn -q validate

script:
  mvn -q package -Dsinai.logs.dir=/var/log/sinai -Dsinai.id.key="$SINAI_ID_KEY"

deploy:
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "build-artifacts.library.ucla.edu"
    local_dir: target/build-artifact
    upload_dir: sinai-web/develop
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    on:
      branch: develop
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "build-artifacts.library.ucla.edu"
    local_dir: target/build-artifact
    upload_dir: sinai-web/stage
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    on:
      branch: stage
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "build-artifacts.library.ucla.edu"
    local_dir: target/build-artifact
    upload_dir: sinai-web/master
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    on:
      branch: master

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: never
  slack:
    secure: eMZgS79kzSH6opY2sSJhrYdTg0jLB/JzLEvQFcn6xoDtek3/WjWWg4+M8sYv/qPqwzY3jeJ0vxd8SIwcgBJkgOHVJqvmqxWV49/F8EOENaDU+oWo5vUUh8GvM1e+B/4wZd14PbD6w9m4qs1gIAUcPECE21p0KDtvN/VYnH+96LI=

sudo: false
