name: Build Artifact Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    env:
      MAVEN_CACHE_KEY: ${{ secrets.MAVEN_CACHE_KEY }}
    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - name: Check out code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@8764a52df183aa0ccea74521dfd9d506ffc7a19a # v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      # If running locally in act, install Maven
      - name: Set up Maven if needed
        if: ${{ env.ACT }}
        uses: stCarolas/setup-maven@1d56b37995622db66cce1214d81014b09807fb5a # v4
        with:
          maven-version: 3.6.3
      - name: Set up Maven cache
        uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a # v2
        if: ${{ env.MAVEN_CACHE_KEY }}
        with:
          path: ~/.m2
          key: uclalibrary-cache-${{ secrets.MAVEN_CACHE_KEY }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: uclalibrary-cache-${{ secrets.MAVEN_CACHE_KEY }}-
      - name: Build with Maven
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_goals_phases: "package"
          maven_profiles: default
          maven_args: >
            -V -ntp -Dsinai.logs.dir=/var/log/sinai -Dsinai.id.key=${{ secrets.SINAI_ID_KEY }}
      - name: Upload build artifact
        uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # v0.5.1
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: build-artifacts.library.ucla.edu
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          SOURCE_DIR: ./target/build-artifact
          DEST_DIR: /sinai-web/master
